---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration for Magento
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Move default nginx configuration file
  command: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.old creates=/etc/nginx/sites-available/default.old
  notify: restart nginx